# Generated by Django 6.0.5 on 2026-05-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidoitem_plato_alter_pedido_total_and_more'),
        ('reservas', '0002_mesa_alter_reserva_estado_reserva_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='reservas.reserva'),
        ),
    ]
