# Generated by Django 6.0.5 on 2026-05-14 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientoinventario_options_and_more'),
        ('menu', '0004_alter_ingrediente_options_alter_plato_options_and_more'),
        ('pedidos', '0004_pedido_reserva'),
        ('reservas', '0003_alter_mesa_estado_alter_mesa_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedido'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.plato', verbose_name='Plato'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
    ]
