# Generated by Django 5.0.2 on 2026-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del plato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('categoria', models.CharField(choices=[('entradas', 'Entradas'), ('platos_principales', 'Platos Principales'), ('postres', 'Postres'), ('bebidas', 'Bebidas')], max_length=20, verbose_name='Categoría')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
