# Generated by Django 5.0.2 on 2026-05-14 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlatoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
            options={
                'verbose_name': 'Ingrediente del plato',
                'verbose_name_plural': 'Ingredientes del plato',
                'unique_together': {('plato', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='platos', through='menu.PlatoIngrediente', to='menu.ingrediente'),
        ),
        migrations.CreateModel(
            name='PrecioPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='menu.plato')),
            ],
            options={
                'verbose_name': 'Precio de plato',
                'verbose_name_plural': 'Precios de platos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
