# Generated by Django 6.0.5 on 2026-05-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_plato_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del ingrediente')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidades')], default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlatoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad necesaria')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingrediente', verbose_name='Ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Ingrediente del Plato',
                'verbose_name_plural': 'Ingredientes del Plato',
                'unique_together': {('plato', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.ManyToManyField(related_name='platos', through='menu.PlatoIngrediente', to='menu.ingrediente', verbose_name='Ingredientes'),
        ),
    ]
