# Generated by Django 5.0.2 on 2026-05-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_plato'),
        ('menu', '0002_ingrediente_platoingrediente_plato_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='producto_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='inventario.producto'),
        ),
    ]
