# Generated by Django 6.0.5 on 2026-05-14 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_ingrediente_producto_inventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['nombre'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='platoingrediente',
            options={'verbose_name': 'Dish Ingredient', 'verbose_name_plural': 'Dish Ingredients'},
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='producto_inventario',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidad',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Stock'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('unit', 'Units')], default='unit', max_length=20, verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ingredient Name'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('starters', 'Entradas'), ('main_courses', 'Platos Fuertes'), ('desserts', 'Postres'), ('drinks', 'Bebidas')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='ingredientes',
            field=models.ManyToManyField(related_name='platos', through='menu.PlatoIngrediente', to='menu.ingrediente', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Dish Name'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='platoingrediente',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Required Quantity'),
        ),
        migrations.AlterField(
            model_name='platoingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingrediente', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='platoingrediente',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato', verbose_name='Dish'),
        ),
        migrations.DeleteModel(
            name='PrecioPlato',
        ),
    ]
