# Generated by Django 6.0.5 on 2026-05-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_ingrediente_producto_inventario'),
        ('menu', '0004_alter_ingrediente_options_alter_plato_options_and_more'),
    ]

    operations = [
    ]
