# Generated by Django 6.0.5 on 2026-05-14 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_ingrediente_options_alter_plato_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='producto_inventario',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidad',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PrecioPlato',
        ),
    ]
