# Generated by Django 5.0.2 on 2026-05-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('menu', '0002_ingrediente_platoingrediente_plato_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='plato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_inventario', to='menu.plato'),
        ),
    ]
