# Generated by Django 6.0.5 on 2026-05-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_plato'),
        ('inventario', '0003_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
    ]
